name: CI

on:
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24
    - name: Render Terraform docs
      uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
      with:
        config-file: .terraform-docs.yaml
    - name: Ensure docs are up to date
      run: |
        npx --yes prettier@3.8.3 --write '**/*.md'
        git diff --exit-code HEAD

  terraform-module:
    name: Verify Terraform (module)
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0

  terraform-example:
    name: Verify Terraform (complete example)
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
    with:
      terraform-version-file: .terraform-version
      working-directory: examples/complete

  release:
    name: Release?
    needs: [ verify, terraform-module, terraform-example ]
    permissions:
      contents: write
      pull-requests: write
    uses: unfunco/meta/.github/workflows/release-please.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
